### PR TITLE
Serverless

### PR DESCRIPTION
**Pull request by SaiArrow**

### CODE REVIEW

**Comment by domoritz** [comment]
Can you describe the pull request if you assign it to me for review?

**Comment by SaiArrow** [comment]
@domoritz 

So this is a server-less version of the vega-transform-db code, in this version instead of sending of sending a request to the server we would directly interact with the database. 
However I guess this code would just be archived since our current optimizer plan assumes a server, I was hoping you could go over the code once then I would close the request instead of merging it.

**Comment by domoritz** [comment]
> However I guess this code would just be archived since our current optimizer plan assumes a server, I was hoping you could go over the code once then I would close the request instead of merging it.

I'm not sure I follow. Would we use this code? If not, I don't think I need to review it.

**Comment by SaiArrow** [comment]
@domoritz 
Could you please take a look at this as well ? (I think we decided to switch over to thee server-less version of the code)

**Comment by domoritz** [comment]
By severless, you mean using duckdb? We still have a server component that the frontend connects to, right?

**Review by domoritz — APPROVED** [review]

**Pull request merged**
